# Copyright 2024 Lutz Behnke
#

name: Build Image

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

#env:
#  GO_MODULE: github.com/finleap-connect/monoskope
#  GO_VERSION: 1.19.x
#  GINKGO_VERSION: v1.16.5
#  GO_CI_LINT_VERSION: v1.48.0

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.gen_bd.outputs.BUILD_DATE }}
    steps:
      - name: set values
        id: gen_bd
        run: |
          echo -n "BUILD_DATE=" >> $GITHUB_OUTPUT
          date +"%y%m%d" >> $GITHUB_OUTPUT
  image:
    needs: [set-vars]

    env:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}
      BUILD_DATE: ${{ needs.set-vars.outputs.build_date }}

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Log in to github registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/unifi-network
          tags: |
            type=ref,event=tag
            type=raw,value=0.0.0-{{sha}}
            type=raw,latest
  
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./deploy/docker
          file: deploy/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}]
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            
            
